---
# Debian tasks file for update_pkgs

- name: Update package cache.
  apt:
    update_cache: yes
    cache_valid_time: 3600
    
- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Remove packages that are nolonger required from the cache
  apt:
    autoclean: yes

- name: Remove package dependencies that are no longer required
  apt:
    autoremove: yes
