---
- name: Perform a dist-upgrade.
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true

- block:
  - name: Check if a reboot is required.
    ansible.builtin.stat:
      path: /var/run/reboot-required
      get_md5: false
    register: reboot_required_file

  # - name: Report reboot_required
  #   debug:
  #     msg: "{{  reboot_required_file.stat.exists | bool }} "
  #   changed_when: reboot_required_file.stat.exists == false
  #   check_mode: false

  - name: Reboot the server (if required).
    ansible.builtin.reboot:
    when: reboot_required_file.stat.exists == true

  when: upk_server_reboot | bool

- name: Remove packages that are no longer required from the cache.
  ansible.builtin.apt:
    autoclean: true

- name: Remove package dependencies that are no longer required.
  ansible.builtin.apt:
    autoremove: true
