---
# RedHat 7 tasks file for update_pkgs

- name: Update all packages to the latest version
  dnf:
    name: '*'
    state: latest
    update_cache: yes

- name: Remove package dependencies that are no longer required
  dnf:
    autoremove: yes
